### ISSUE TITLE
Building instructions don't work on Linux

### ISSUE THREAD

**Issue by reuseman** [cpp-core/sort#1]
Hey @melton1968, it's reuseman from Stackoverflow. The sort library is really coming out nice. I've tried to compile with your building instructions both on Fedora 36 and Ubuntu 22.04, and for some reason the compiler cannot found out of the box the std library. Here it is the error:

```
[  1%] Building CXX object _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o
In file included from /home/reuseman/temp/sort/build/_deps/date-src/src/tz.cpp:86:
In file included from /home/reuseman/temp/sort/build/_deps/date-src/include/date/tz_private.h:31:
In file included from /home/reuseman/temp/sort/build/_deps/date-src/include/date/tz.h:99:
/home/reuseman/temp/sort/build/_deps/date-src/include/date/date.h:43:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
make[3]: *** [_deps/date-build/CMakeFiles/date-tz.dir/build.make:76: _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:796: _deps/date-build/CMakeFiles/date-tz.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:355: CMakeFiles/sort1.dir/rule] Error 2
make: *** [Makefile:195: sort1] Error 2

```

**Comment by melton1968** [comment]
My first guess is a problem with `libc++` or the compiler configuration. On Ubuntu 20.04, I find `<cassert>` here:

```
/usr/include/c++/v1/cassert
```

Can you compile a simple program that includes `<cassert>`?

This is how I installed`clang-15` and related libraries:

```
apt install clang-15 libc++-15-dev libc++abi-15-dev
```

Here is the beginning of what I get when I configure and build on Ubuntu 20.04 using `clang-15`:

Configuration:
```
$ CC=clang-15 CXX=clang++-15 cmake -DCMAKE_INSTALL_PREFIX=~/opt ..
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/bin/clang-15
...
```

Build:
```
$ VERBOSE=1 make sort1
/home/mmelton/bin/cmake -S/home/mmelton/work/sort -B/home/mmelton/work/sort/build --check-build-\
system CMakeFiles/Makefile.cmake 0
make  -f CMakeFiles/Makefile2 sort1
make[1]: Entering directory '/home/mmelton/work/sort/build'
/home/mmelton/bin/cmake -S/home/mmelton/work/sort -B/home/mmelton/work/sort/build --check-build-\
system CMakeFiles/Makefile.cmake 0
/home/mmelton/bin/cmake -E cmake_progress_start /home/mmelton/work/sort/build/CMakeFiles 52
make  -f CMakeFiles/Makefile2 CMakeFiles/sort1.dir/all
make[2]: Entering directory '/home/mmelton/work/sort/build'
make  -f _deps/date-build/CMakeFiles/date-tz.dir/build.make _deps/date-build/CMakeFiles/date-tz.\
dir/depend
make[3]: Entering directory '/home/mmelton/work/sort/build'
cd /home/mmelton/work/sort/build && /home/mmelton/bin/cmake -E cmake_depends "Unix Makefiles" /h\
ome/mmelton/work/sort /home/mmelton/work/sort/build/_deps/date-src /home/mmelton/work/sort/build\
 /home/mmelton/work/sort/build/_deps/date-build /home/mmelton/work/sort/build/_deps/date-build/C\
MakeFiles/date-tz.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/mmelton/work/sort/build'
make  -f _deps/date-build/CMakeFiles/date-tz.dir/build.make _deps/date-build/CMakeFiles/date-tz.\
dir/build
make[3]: Entering directory '/home/mmelton/work/sort/build'
[  1%] Building CXX object _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o
cd /home/mmelton/work/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DHAS\
_REMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/mmelton/work/sort/build/_dep\
s/date-src/include -fPIC -Wall -stdlib=libc++ -g -O -std=c++17 -MD -MT _deps/date-build/CMakeFil\
es/date-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.dir/\
src/tz.cpp.o -c /home/mmelton/work/sort/build/_deps/date-src/src/tz.cpp
[  3%] Linking CXX static library libdate-tz.a
```

**Comment by melton1968** [comment]
Also, I recall that to install `clang-15` on Ubuntu 20.04, I had to manually update the repos:

```
$ wget https://apt.llvm.org/llvm.sh
$ sudo ./llvm.sh 15
$ apt update
```

**Comment by reuseman** [comment]
Still doesn't work, but if I create a simple `cpp` file with the `cassert` header, it can be trivially compiled by clang-15.

This is what I've done.

CMake output
```
> CC=clang-15 CXX=clang++-15 cmake -DCMAKE_INSTALL_PREFIX=~/opt ..
-- The C compiler identification is Clang 15.0.7
-- The CXX compiler identification is Clang 15.0.7
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /usr/bin/clang-15
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-15 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-15 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.40.0") 
-- sort: Configuration: /home/reuseman/temp/sort
-- sort: Included from: /home/reuseman/temp/sort
-- sort: Install prefix: /home/reuseman/opt
-- sort: test ON
-- sort: docs OFF
-- stream: Searching for stream::stream
-- stream: Fetching from repo: stream
-- stream: Configuration: /home/reuseman/temp/sort/build/_deps/stream-src
-- stream: Included from: /home/reuseman/temp/sort
-- stream: Install prefix: /home/reuseman/opt
-- stream: test OFF
-- stream: docs OFF
-- tuple: Searching for tuple::tuple
-- tuple: Fetching from repo: tuple
-- tuple: Configuration: /home/reuseman/temp/sort/build/_deps/tuple-src
-- tuple: Included from: /home/reuseman/temp/sort
-- tuple: Install prefix: /home/reuseman/opt
-- tuple: Binary dir: /home/reuseman/temp/sort/build
-- tuple: core dir: 
-- tuple: test OFF
-- tuple: docs OFF
-- mp: Searching for mp::mp
-- mp: Fetching from repo: mp
-- mp: Configuration: /home/reuseman/temp/sort/build/_deps/mp-src
-- mp: Included from: /home/reuseman/temp/sort
-- mp: Install prefix /home/reuseman/opt
-- mp: test OFF
-- mp: docs OFF
-- fmt: Searching for fmt::fmt
-- fmt: Fetching from repo: fmt
-- Module support is disabled.
-- Version: 9.1.0
-- Build type: Release
-- CXX_STANDARD: 20
-- Performing Test has_std_20_flag
-- Performing Test has_std_20_flag - Success
-- Performing Test has_std_2a_flag
-- Performing Test has_std_2a_flag - Success
-- Required features: cxx_variadic_templates
-- Performing Test HAS_NULLPTR_WARNING
-- Performing Test HAS_NULLPTR_WARNING - Success
-- pp: Searching for pp::pp
-- pp: Fetching from repo: pp
-- pp: Configuration: /home/reuseman/temp/sort/build/_deps/pp-src
-- pp: Included from: /home/reuseman/temp/sort
-- pp: Install prefix: /home/reuseman/opt
-- pp: Project source dir: /home/reuseman/temp/sort/build/_deps/pp-src
-- pp: Project binary dir: /home/reuseman/temp/sort/build/_deps/pp-build
-- pp: Cmake binary dir: /home/reuseman/temp/sort/build
-- pp: test: OFF
-- pp: docs: OFF
-- fp: Searching for fp::fp
-- fp: Fetching from repo: fp
-- fp: Configuration: /home/reuseman/temp/sort/build/_deps/fp-src
-- fp: Included from: /home/reuseman/temp/sort
-- fp: Install prefix: /home/reuseman/opt
-- fp: test OFF
-- fp: docs OFF
-- util: Searching for util::util
-- util: Fetching from repo: util
-- util: Configuration: /home/reuseman/temp/sort/build/_deps/util-src
-- util: Included from: /home/reuseman/temp/sort
-- util: Install prefix: /home/reuseman/opt
-- util: test OFF
-- util: docs OFF
-- string: Searching for string::string
-- string: Fetching from repo: string
-- string: Configuration: /home/reuseman/temp/sort/build/_deps/string-src
-- string: Included from: /home/reuseman/temp/sort
-- string: Install prefix /home/reuseman/opt
-- string: test OFF
-- string: docs OFF
-- json: Searching for nlohmann_json::nlohmann_json
-- json: Fetching from repo: json
-- Using the multi-header code from /home/reuseman/temp/sort/build/_deps/json-src/include/
-- chrono: Searching for chrono::chrono
-- chrono: Fetching from repo: chrono
-- chrono: Configuration: /home/reuseman/temp/sort/build/_deps/chrono-src
-- chrono: Included from: /home/reuseman/temp/sort
-- chrono: Install prefix: /home/reuseman/opt
-- chrono: test OFF
-- chrono: docs OFF
-- date: Searching for date::date-tz
-- date: Fetching from repo: date
# date: USE_SYSTEM_TZ_DB ON
# date: MANUAL_TZ_DB OFF
# date: USE_TZ_DB_IN_DOT OFF
# date: BUILD_SHARED_LIBS OFF
# date: ENABLE_DATE_TESTING OFF
# date: DISABLE_STRING_VIEW OFF
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done (51.9s)
-- Generating done (0.0s)
-- Build files have been written to: /home/reuseman/temp/sort/build
```

Make output
```
x VERBOSE=1 make sort1
/usr/bin/cmake -S/home/reuseman/temp/sort -B/home/reuseman/temp/sort/build --check-build-system CMakeFiles/Makefile.cmake 0
make  -f CMakeFiles/Makefile2 sort1
make[1]: Entering directory '/home/reuseman/temp/sort/build'
/usr/bin/cmake -S/home/reuseman/temp/sort -B/home/reuseman/temp/sort/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/reuseman/temp/sort/build/CMakeFiles 52
make  -f CMakeFiles/Makefile2 CMakeFiles/sort1.dir/all
make[2]: Entering directory '/home/reuseman/temp/sort/build'
make  -f _deps/date-build/CMakeFiles/date-tz.dir/build.make _deps/date-build/CMakeFiles/date-tz.dir/depend
make[3]: Entering directory '/home/reuseman/temp/sort/build'
cd /home/reuseman/temp/sort/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/reuseman/temp/sort /home/reuseman/temp/sort/build/_deps/date-src /home/reuseman/temp/sort/build /home/reuseman/temp/sort/build/_deps/date-build /home/reuseman/temp/sort/build/_deps/date-build/CMakeFiles/date-tz.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/home/reuseman/temp/sort/build'
make  -f _deps/date-build/CMakeFiles/date-tz.dir/build.make _deps/date-build/CMakeFiles/date-tz.dir/build
make[3]: Entering directory '/home/reuseman/temp/sort/build'
[  1%] Building CXX object _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o
cd /home/reuseman/temp/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DHAS_REMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/reuseman/temp/sort/build/_deps/date-src/include -std=c++17 -fPIC -Wall -stdlib=libc++ -g -O -MD -MT _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.dir/src/tz.cpp.o -c /home/reuseman/temp/sort/build/_deps/date-src/src/tz.cpp
In file included from /home/reuseman/temp/sort/build/_deps/date-src/src/tz.cpp:86:
In file included from /home/reuseman/temp/sort/build/_deps/date-src/include/date/tz_private.h:31:
In file included from /home/reuseman/temp/sort/build/_deps/date-src/include/date/tz.h:99:
/home/reuseman/temp/sort/build/_deps/date-src/include/date/date.h:43:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
make[3]: *** [_deps/date-build/CMakeFiles/date-tz.dir/build.make:76: _deps/date-build/CMakeFiles/date-tz.dir/src/tz.cpp.o] Error 1
make[3]: Leaving directory '/home/reuseman/temp/sort/build'
make[2]: *** [CMakeFiles/Makefile2:796: _deps/date-build/CMakeFiles/date-tz.dir/all] Error 2
make[2]: Leaving directory '/home/reuseman/temp/sort/build'
make[1]: *** [CMakeFiles/Makefile2:355: CMakeFiles/sort1.dir/rule] Error 2
make[1]: Leaving directory '/home/reuseman/temp/sort/build'
make: *** [Makefile:195: sort1] Error 2
```

**Comment by melton1968** [comment]
Hmm ... I'm stumped. The compilation commands are exactly the same between our two builds (except for the home directories). And, `data.cpp` does include `<cassert>` at lines 43. There must be some difference in our environments.

I added a GitHub action that builds `sort1` whenever a commit is made to the `main` branch.  You will notice a status badge on the main page. It builds on successfully on Ubuntu and those logs may be helpful.

```
cd /home/mmelton/work/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DH\
AS_REMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/mmelton/work/sort/build/_d\
eps/date-src/include -std=c++17 -fPIC -Wall -stdlib=libc++ -g -O -MD -MT _deps/date-build/CMakeF\
iles/date-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.di\
r/src/tz.cpp.o -c /home/mmelton/work/sort/build/_deps/date-src/src/tz.cpp

```
```
cd /home/reuseman/temp/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DHAS_R\
EMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/reuseman/temp/sort/build/_deps/da\
te-src/include -std=c++17 -fPIC -Wall -stdlib=libc++ -g -O -MD -MT _deps/date-build/CMakeFiles/date\
-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.dir/src/tz.cpp\
.o -c /home/reuseman/temp/sort/build/_deps/date-src/src/tz.cpp
```

What happends if you create the file `build/t.cpp` with the following content:

```
#include <cassert>

void foo() {
}
```

And, then run the slightly modified compilation command:

```
cd /home/reuseman/temp/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DHAS_R\
EMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/reuseman/temp/sort/build/_deps/da\
te-src/include -std=c++17 -fPIC -Wall -stdlib=libc++ -g -O -MD -MT _deps/date-build/CMakeFiles/date\
-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.dir/src/tz.cpp\
.o -c /home/reuseman/temp/sort/build/t.cpp
```

**Comment by reuseman** [comment]
If I create the `build/t.cpp` with that content, then I get this
```
x cd /home/reuseman/temp/sort/build/_deps/date-build && /usr/bin/clang++-15 -DAUTO_DOWNLOAD=0 -DHAS_R\
EMOTE_API=0 -DINSTALL=. -DONLY_C_LOCALE=0 -DUSE_OS_TZDB=1 -I/home/reuseman/temp/sort/build/_deps/da\
te-src/include -std=c++17 -fPIC -Wall -stdlib=libc++ -g -O -MD -MT _deps/date-build/CMakeFiles/date\
-tz.dir/src/tz.cpp.o -MF CMakeFiles/date-tz.dir/src/tz.cpp.o.d -o CMakeFiles/date-tz.dir/src/tz.cpp\
.o -c /home/reuseman/temp/sort/build/t.cpp
/home/reuseman/temp/sort/build/t.cpp:1:10: fatal error: 'cassert' file not found
#include <cassert>
         ^~~~~~~~~
1 error generated.
```

But with a simple `a.cpp` that contains
```
#include <cassert>

int main(int argc, char* argv[]) {
	return 0;
}
```

and compiled with `clang++-15 a.cpp`, everything works nice

**Comment by reuseman** [comment]
Ok, I've just managed to solve by looking at the compilation commands. I usually use gcc, and apparently on my Fedora 36 machine `libcxx-devel` was missing. So a simple `sudo dnf install libcxx-devel` was enough to solve the problem.

Thanks for the support!
